Repository z-fitch/little-shop-7, pull requests merged in 2023-07, with the labels that each got.

#3 1 database setup
  app/models/customer.rb
  db/migrate/20230725002338_create_customer.rb
  db/migrate/20230725010247_create_invoice_items.rb
  db/migrate/20230725010705_create_items.rb
  db/migrate/20230725010747_create_invoices.rb
  db/migrate/20230725010852_create_transactions.rb
  db/migrate/20230725011646_create_merchants.rb
  db/migrate/20230725011742_add_item_to_invoice_items.rb
  db/migrate/20230725011752_add_invoice_to_invoice_items.rb
  db/migrate/20230725011806_add_merchant_to_items.rb
  db/migrate/20230725011817_add_invoice_to_transactions.rb
  db/migrate/20230725012122_add_customer_to_invoices.rb
  db/schema.rb
  lib/tasks/csv_load.rake
  spec/models/customer_spec.rb
Labels: enhancement

#14 13 transaction model
  Gemfile
  Gemfile.lock
  app/models/invoice.rb
  app/models/transaction.rb
  spec/models/invoice_spec.rb
  spec/models/transaction_spec.rb
  spec/rails_helper.rb
Labels: bug, enhancement

#25 Feat: Admin dashboard now has merchants and invoices
  app/controllers/admin/dashboard_controller.rb
  app/controllers/admin_controller.rb
  app/views/admin/dashboard/index.html.erb
  app/views/admin/index.html.erb
  config/routes.rb
  spec/features/admin/dashboard_spec.rb
Labels: enhancement

#28 Story22
  app/controllers/admin/invoices_controller.rb
  app/controllers/admin_controller.rb
  app/models/invoice.rb
  app/models/invoice_item.rb
  app/views/admin/index.html.erb
  app/views/admin/invoices/show.html.erb
  spec/features/admin/dashboard_spec.rb
  spec/models/invoice_spec.rb
  spec/models/merchant_spec.rb
Labels: enhancement

#30 US_21
  app/controllers/admin_controller.rb
  app/models/customer.rb
  app/views/admin/index.html.erb
  config/routes.rb
  spec/features/admin/dashboard_spec.rb
  spec/models/customer_spec.rb
Labels: enhancement

#42 31 23 admin dashboard invoices sorted by least recent
  app/models/customer.rb
  app/models/invoice.rb
  app/views/admin/index.html.erb
  spec/features/admin/dashboard_spec.rb
  spec/models/invoice_spec.rb
Labels: enhancement

#45 Story26j2
  app/controllers/admin/merchants_controller.rb
  app/views/admin/merchants/edit.html.erb
  app/views/admin/merchants/index.html.erb
  app/views/admin/merchants/show.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  spec/features/admin/admin_merchant_spec.rb
Labels: enhancement

#49 Story 14: Merchant Invoices Index
  app/controllers/merchant_invoices_controller.rb
  app/models/merchant.rb
  app/views/merchant_invoices/index.html.erb
  config/routes.rb
  spec/features/merchants/invoices/index_spec.rb
  spec/models/merchant_spec.rb
Labels: enhancement

#51 #5 & #6 Merchant items index
  app/controllers/merchant_items_controller.rb
  app/models/item.rb
  app/views/merchant_items/index.html.erb
  app/views/merchant_items/show.html.erb
  config/routes.rb
  spec/features/merchants/merchant_items/index_spec.rb
  spec/features/merchants/merchant_items/show_spec.rb
  spec/models/item_spec.rb
Labels: bug, enhancement

#56 54 29 admin merchant create
  app/controllers/admin/merchants_controller.rb
  app/models/merchant.rb
  app/views/admin/merchants/_admin_header.html.erb
  app/views/admin/merchants/_new_edit.html.erb
  app/views/admin/merchants/index.html.erb
  app/views/admin/merchants/new.html.erb
  config/routes.rb
  db/migrate/20230728223332_add_status_to_merchants.rb
  db/schema.rb
  spec/features/admin/merchants/index_spec.rb
  spec/features/admin/merchants/show_spec.rb
  spec/features/merchants/invoices/index_spec.rb
  spec/models/merchant_spec.rb
Labels: enhancement

#59 Story #8 Items update
  app/controllers/application_controller.rb
  app/controllers/merchant_items_controller.rb
  app/models/item.rb
  app/views/merchant_items/edit.html.erb
  app/views/merchant_items/show.html.erb
  config/routes.rb
  spec/features/merchants/merchant_items/show_spec.rb
  spec/models/invoice_spec.rb
  spec/models/item_spec.rb
  spec/models/merchant_spec.rb
Labels: enhancement

#68 Story 15: Merchant Invoice Show Page
  app/controllers/merchant_invoices_controller.rb
  app/models/invoice.rb
  app/views/merchant_invoices/show.html.erb
  spec/features/merchants/invoices/show_spec.rb
  spec/models/merchant_spec.rb
Labels: bug, enhancement

#70 Adds testing for US_28
  spec/features/admin/merchants/index_spec.rb
Labels: enhancement

#66 Stories 30+31: Admin Merchants: Top 5 Merchants by Revenue AND Top Merchant's Best Day
  app/models/merchant.rb
  app/views/admin/merchants/index.html.erb
  spec/features/admin/merchants/index_spec.rb
  spec/models/merchant_spec.rb
  spec/rails_helper.rb
Labels: enhancement

#74 when i merged the story 30/31 it broke the code. I added description …
  spec/rails_helper.rb
Labels: bug

#72 Story #9 + #10 Merchant Item Disable/Enable; Merchant Items Grouped by Status
  app/controllers/merchant_items_controller.rb
  app/models/item.rb
  app/views/merchant_items/index.html.erb
  db/migrate/20230729220018_add_status_to_items.rb
  db/schema.rb
  spec/features/merchants/merchant_items/index_spec.rb
  spec/models/item_spec.rb
Labels: enhancement

#67 Story 32- 35: Admin Invoice index and Show Pages
  app/controllers/admin/invoices_controller.rb
  app/models/invoice.rb
  app/models/invoice_item.rb
  app/views/admin/invoices/index.html.erb
  app/views/admin/invoices/show.html.erb
  app/views/admin/merchants/index.html.erb
  spec/features/admin/admin_invoice_index_spec.rb
  spec/features/admin/admin_invoice_show_spec.rb
  spec/features/admin/merchants/index_spec.rb
  spec/features/admin/merchants/show_spec.rb
  spec/models/invoice_item_spec.rb
  spec/models/invoice_spec.rb
  spec/models/merchant_spec.rb
Labels: enhancement
